title: Davina Stephens
subtitle: ""
description: ""
keywords:
lang: en
version: 0.0.3
baseurl: ""
url: "https://davina.junglestar.org"
menu: long_menu # 'short_menu' or 'long_menu'
qr: show # 'show' or 'hide' put qr.svg in includes/defs.html call it: icn--qr

company:
  name:  #
  legal_name: #if overrides 'company.name' in footer
  email: davinastephensart@gmail.com
  telephone:
  telephone_whatsapp: +1 208 309 0921 #
  fax: #
  address:
  maplink: #
  country: #
  twitter: #
  facebook_page: https://web.facebook.com/davinastephensart
  youtube:
  instagram: https://www.instagram.com/davinastephensart/
  vimeo:
  booking: #complete URL
  airbnb: #complete URL
  gplus: #
  tumblr: #
  soundcloud: #complete URL

#SEO https://jekyll.github.io/jekyll-seo-tag/usage/
#
# SEO tag will use the YAML front matter if included in a post, page, or document:
#
# title
# description
# image - (e.g., /assets/page-pic.jpg)
# author - Page-specific author (see below)
# lang - Page-specific language

author: rokma
twitter:
  username: rokmatwit
facebook:
  app_id: #Facebook app ID for Facebook insights
  publisher: #Facebook page URL or ID of the publishing entity
  admins: #Facebook user ID for domain insights linked to a personal account
logo: /assets/favicons/apple-touch-icon-152x152.png

google:
  analytics:
  verification: google32e66f1a5601ec40

# Build settings
markdown: kramdown
plugins:
 - jekyll-seo-tag
 - jekyll-sitemap
 - html-proofer

exclude:
  - Gemfile.lock
  - node_modules
  - package-lock.json
  - Gemfile

permalink: /:title/ # pretty

collections:
 series:
  output: true
  permalink: /:title/
 pages:
  output: true
  permalink: /:title/
 paintings:
  output: true
  permalink: /:title/


defaults:
  - scope:
      path: ""
      type: "paintings"
    values:
      layout: "painting"
